### ISSUE TITLE
使用 hexo g 生成时报错 TypeError 和 cannot read property 'enable' of undefined

### ISSUE THREAD

**Issue by ITISummer** [meethigher/hexo-theme-starry#2]
$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 69 ms
ERROR TypeError: E:\HexoBlog\themes\starry\layout\post.ejs:18
    16|             <span class="post-share-btn">分享</span>
    17|         </div>
 >> 18|         <%- partial("_partial/comment.ejs") %>
    19|         <% if (theme.Footer.counter){ %>
    20|             <div class="busuanzi">
    21|                 <span id="busuanzi_container_page_pv">阅读量<span id="busuanzi_value_page_pv"></span>次</span>

E:\HexoBlog\themes\starry\layout\_partial\comment.ejs:1
 >> 1| <% if (page.comments && theme.gitalk.enable){ %>
    2| <div class="post-comment"><span class="instruction">若无法评论请科学上网</span><div id="gitalk-container"></div></div>
    3| <link rel="stylesheet" href="<%- url_for("css/gitalk.css") %>">
    4| <script src="<%- url_for("js/gitalk.js") %>"></script>

Cannot read property 'enable' of undefined
    at eval (E:\HexoBlog\themes\starry\layout\_partial\comment.ejs:8:42)
    at comment (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (E:\HexoBlog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (E:\HexoBlog\themes\starry\layout\post.ejs:39:17)
    at post (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\HexoBlog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\HexoBlog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\HexoBlog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:469:10)
    at resume_ (_stream_readable.js:983:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'E:\\HexoBlog\\themes\\starry\\layout\\post.ejs'
}
ERROR {
  err: TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
      16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
      17| <%- js("js/meethigher.js") %>
   >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
      19| </body>
      20| </html>

  Cannot read property 'enable' of undefined
      at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
      at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
  }
} Render HTML failed: archives/index.html
ERROR {
  err: TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
      16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
      17| <%- js("js/meethigher.js") %>
   >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
      19| </body>
      20| </html>

  Cannot read property 'enable' of undefined
      at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
      at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
  }
} Render HTML failed: archives/2021/index.html
ERROR {
  err: TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
      16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
      17| <%- js("js/meethigher.js") %>
   >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
      19| </body>
      20| </html>

  Cannot read property 'enable' of undefined
      at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
      at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
  }
} Render HTML failed: archives/2021/04/index.html
ERROR TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
    16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
    17| <%- js("js/meethigher.js") %>
 >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
    19| </body>
    20| </html>

Cannot read property 'enable' of undefined
    at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
    at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
}
ERROR TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
    16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
    17| <%- js("js/meethigher.js") %>
 >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
    19| </body>
    20| </html>

Cannot read property 'enable' of undefined
    at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
    at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
}
ERROR TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
    16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
    17| <%- js("js/meethigher.js") %>
 >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
    19| </body>
    20| </html>

Cannot read property 'enable' of undefined
    at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
    at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
}
ERROR {
  err: TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
      16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
      17| <%- js("js/meethigher.js") %>
   >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
      19| </body>
      20| </html>

  Cannot read property 'enable' of undefined
      at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
      at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
      at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
      at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
      at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
      at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
  }
} Render HTML failed: index.html
ERROR TypeError: E:\HexoBlog\themes\starry\layout\layout.ejs:18
    16| <%- js("https://cdn.jsdelivr.net/gh/meethigher/cdn@13/js/instantpage.js") %>
    17| <%- js("js/meethigher.js") %>
 >> 18| <% if (theme.lazyload.enable){ %><script>let imgs = $(".post-content.blog-markdown img");imgs.css("width", "100%");</script><% } %>
    19| </body>
    20| </html>

Cannot read property 'enable' of undefined
    at eval (E:\HexoBlog\themes\starry\layout\layout.ejs:51:27)
    at layout (E:\HexoBlog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (E:\HexoBlog\node_modules\hexo\lib\theme\view.js:39:17)
    at E:\HexoBlog\node_modules\hexo\lib\theme\view.js:51:25
    at tryCatcher (E:\HexoBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (E:\HexoBlog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (E:\HexoBlog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (E:\HexoBlog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (E:\HexoBlog\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\HexoBlog\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  path: 'E:\\HexoBlog\\themes\\starry\\layout\\layout.ejs'
}
INFO  0 files generated in 25 ms

**Comment by meethigher** [comment]
# 这个是node模块的插件问题，新插件不兼容旧版插件，这边我就没进行更新了，因为我自己一直用的老插件。
